# Site settings
title: datealive
SEOTitle: datealive的博客 | zrf blog
header-img: img/post-bg-desk.jpg
email: 2448282543@qq.com
description: "better late than never."
keyword: "zrf, zrf Blog, datealive的博客, zhangrenfeng, 张壬丰, iOS, Apple, iPhone"
url: "http://dateolive.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/dateolive/dateolive.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
#sidebar-avatar:/img/avatar-m.JPG      # use absolute URL, seeing it's used in both `/` and `/about/`








# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: datealive

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: da2e2076661d99628fe7                            #生成的clientID
  clientSecret: f292a91f6e1b14a83126b2429e217afaac4028bc    #生成的clientSecret
  repo: dateolive.github.io    #仓库名称
  owner: datealive    #github用户名
  admin: datealive
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


live2d:
  enable: true   # 开启
  scriptFrom: local # 默认
  model:
    use: live2d-widget-model-wanko   # 对应人物模型包名
  display:
    position: left     # 处于屏幕左下方
    width: 60         # 大小
    height: 120
  mobile:
    show: true

# SNS settings
RSS: false
weibo_username:     梦回datealive
zhihu_username:     datealive
github_username:    dateolive
facebook_username:  datealive
jianshu_username:   datealive


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true




